# changes to documentation generation
"area/doc-gen":
  - changed-files:
      - any-glob-to-any-file: ["doc/**/*"]

# changes to the core Go cobra lib package
"area/lib":
  - changed-files:
      - any-glob-to-any-file: ["./*.go"]

# changes to GitHub workflows
"area/github":
  - changed-files:
      - any-glob-to-any-file: [".github/**/*"]

# changes to shell completions
"area/*sh completion":
  - changed-files:
      - any-glob-to-any-file: ["./*completions*"]
