theme = "docuapi"
languageCode = "en-us"
baseurl = "https://zulucmd.github.io/zulu/"
title = "Zulu"

disableKinds = ["taxonomyTerm"]

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
pygmentsUseClasses = false

defaultContentLanguage = "en"

[module]
[module.hugoVersion]
[[module.imports]]
# We need one module import for Hugo to detect us as a Hugo Module.
path = "github.com/bep/empty-hugo-module"

[params]
search = true

[markup]
[markup.goldmark]
[markup.goldmark.parser]
autoHeadingIDType = "github-ascii"
[markup.goldmark.renderer]
unsafe = true

[languages]
[languages.en]
languageName = "English"
weight = 2
title = "Zulu documentation"
toc_footers = [
    "[![github.com/gowraden/zulu](https://img.shields.io/badge/-zulucmd/zulu-323131.svg?logo=github&style=flat-square&longCache=true)](https://github.com/zulucmd/zulu)",
    "Built with [Hugo](https://gohugo.io/) theme [DocuAPI](https://github.com/bep/docuapi) by [bep](https://github.com/bep)"
]
[languages.en.blackfriday]
angledQuotes = false
hrefTargetBlank = true
