package doc_test

import (
	"bytes"
	"fmt"
	"strings"
	"time"

	"github.com/zulucmd/zulu/v2"
	"github.com/zulucmd/zulu/v2/doc"
	"github.com/zulucmd/zulu/v2/internal/util"
)

// this is needed due to https://github.com/golang/go/issues/59191
func collapseLines(text string) string {
	lines := strings.Split(text, "\n")
	n := 0
	for _, line := range lines {
		if line != "" || n > 0 && lines[n-1] != "" {
			lines[n] = line
			n++
		}
	}

	lines = lines[0:n]
	if n > 0 && lines[n-1] != "" {
		lines = append(lines, "")
	}
	return strings.Join(lines, "\n")
}

func ExampleGenManTree() {
	cmd := &zulu.Command{
		Use:   "test",
		Short: "my test program",
	}
	header := &doc.GenManHeader{
		Title:   "MINE",
		Section: "3",
	}
	util.CheckErr(doc.GenManTree(cmd, header, "/tmp"))

	// Output:
}

func ExampleGenMan() {
	cmd := &zulu.Command{
		Use:   "test",
		Short: "my test program",
	}
	header := &doc.GenManHeader{
		Title:   "MINE",
		Section: "3",
		Date:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.UTC),
	}
	out := new(bytes.Buffer)
	err := doc.GenMan(cmd, header, out)
	util.CheckErr(err)
	fmt.Print(collapseLines(out.String()))

	// Output:
	// .nh
	// .TH "MINE" "3" "Jan 2020" "Auto generated by zulucmd/zulu" ""
	//
	// .SH NAME
	// test - my test program
	//
	// .SH SYNOPSIS
	// \fBtest [flags]\fP
	//
	// .SH DESCRIPTION
	// my test program
	//
	// .SH OPTIONS
	// \fB-h\fP, \fB--help\fP
	//
	// .EX
	// help for test
	// .EE
	//
	// .SH HISTORY
	// 1-Jan-2020 Auto generated by zulucmd/zulu
}
