name: 'site'

on:
  push:
  pull_request:

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Get Hugo and Theme
        run: |
          HUGO_VERSION=0.101.0
          curl -fsSL https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz | sudo tar xzf - -C /usr/local/bin hugo
          sudo chmod +x /usr/local/bin/hugo
          mkdir -p site/themes
          cd site/themes
          git clone https://github.com/bep/docuapi
          cd docuapi
          npm install --only=dev
          mv node_modules ../..
      - name: Build site
        run: |
          cd site
          hugo version
          hugo
      - uses: actions/upload-artifact@v2
        with:
          name: site
          path: site/public

      - name: Publish site to gh-pages
        if: github.event_name != 'pull_request'
        run: |
          cd site/public/
          touch .nojekyll
          git init
          cp ../../.git/config ./.git/config
          git add .
          git config --local user.email "push@gha"
          git config --local user.name "GHA"
          git commit -a -m "update ${{ github.sha }}"
          git push -u origin +HEAD:gh-pages
