name: 'site'

on:
  push:
    branches:
      - main
    paths:
      - 'site/**'
      - '.github/workflows/site.yml'
  pull_request:
    paths:
      - 'site/**'
      - '.github/workflows/site.yml'

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v7

      - uses: jdx/mise-action@v3
        with:
          install_args: "hugo-extended"
        env:
          MISE_TRUSTED_CONFIG_PATHS: ${{ github.workspace }}

      - name: Build site
        run: |
          cd site
          hugo version
          hugo --gc --minify
      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: site/public

      - name: Publish site to gh-pages
        if: success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        run: |
          cd site/public/
          touch .nojekyll
          git init
          cp ../../.git/config ./.git/config
          git add .
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "update ${{ github.sha }}"
          git push -u origin +HEAD:gh-pages
