name: Test Completions

on:
  push:
    branches: [main]
  pull_request:

env:
  GO111MODULE: on

jobs:
  Test-Docker:
    runs-on: ubuntu-latest
    name: Docker Tests
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v3
        with:
          install_args: "go"
        env:
          MISE_TRUSTED_CONFIG_PATHS: ${{ github.workspace }}
      - uses: actions/cache@v6
        with:
          path: |
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~/AppData/Local/go-build
            ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}
          restore-keys: go-mod
      - name: Run tests
        shell: bash
        run: mise run completion:all
